### ISSUE TITLE
roblox-ts missing from package.json

### ISSUE THREAD

**Issue by ari-party** [PepeElToro41/ui-labs#10]
See title.

**Comment by ari-party** [comment]
Also: ![image](https://github.com/user-attachments/assets/1479faa1-c809-4202-a9a2-43559f70ec97)

**Comment by PepeElToro41** [comment]
oh yeah, I should add roblox-ts thanks.

About the dependencies, not sure why npm marked *that* version as the latest one.

latest version should be @rbxts/ui-labs@2.1.1

**Comment by PepeElToro41** [comment]
edited the tag. Latest version should **now** be *2.1.1*, thanks for the heads up
