### ISSUE TITLE
Button to reset zoom

### ISSUE THREAD

**Issue by OutOfBears** [PepeElToro41/ui-labs#31]
Currently you can zoom in and out but you have no button to reset zoom. It'd be better for UX to not have to manually hit zoom in/out to reset, and have a button to instantly reset zoom back to 100%

**Comment by PepeElToro41** [comment]
Theres a button to reset the view

https://pepeeltoro41.github.io/ui-labs/docs/plugin/visualizing.html#resetting-the-view
