### ISSUE TITLE
Story Checks should use t.interface instead of t.strictInterface

### ISSUE THREAD

**Issue by timechang** [PepeElToro41/ui-labs#32]
Strict interface ends up making errors more confusing than they would be otherwise. If a key exists that shouldn't, there either isn't any harm in it, or if there is it leads to having to comb through the source code to figure out why it keeps saying the story does not have a valid library.

**Comment by timechang** [comment]
An alternative would be to just error more verbosely (saying exactly what key caused it), but you'd probably have to write a function separate from t for that.

**Comment by PepeElToro41** [comment]
yes I probably wont allow extra keys in the story because there's really no point on doing it.

But I will check them on my own to give more informative errors instead of using `t`

**Comment by AshleyJamesy** [comment]
Had to come look through source code and this issue just to find out it was because I had invalid keys in my story. I thought cleanup function was a valid key, was this removed recently?

**Comment by PepeElToro41** [comment]
This now has been fixed here: https://github.com/PepeElToro41/ui-labs/pull/35
