### ISSUE TITLE
[Feature Request] Controls list ordering

### ISSUE THREAD

**Issue by Olaroll** [PepeElToro41/ui-labs#34]
It would be great to have the ability to change the order in which controls are displayed.

For example if I have a `Width` and `Height` control, it makes a lot of sense to keep them together.

I think the simplest solution is to simply sort the controls alphabetically and leave it at that, otherwise an API change would be required.

**Comment by PepeElToro41** [comment]
I was thinking about this for a while, I think the solution would be an `Ordered` function that will insert an Order optional key in the control and return it back

```lua
local controls = {
       Control1 = 10,
       Control2 = Ordered("text", 2),
       Control3 = Ordered(EnumList(), 3)
}
```

**Comment by PepeElToro41** [comment]
Added here https://github.com/PepeElToro41/ui-labs/commit/ac8d5ad56d4e9149d6e8a4fa7abd77a606e9f89e

Will be released in the new update
