### ISSUE TITLE
Add toolbar button for automatically clearing the output

### ISSUE THREAD

**Issue by Nidoxs** [PepeElToro41/ui-labs#46]
I think it would be really useful to have a toggleable option to **clear** the Studio output when a story is reloaded. I usually have the output open somewhere on my screen to monitor issues that may arise in my story code while iterating on them.

It can be a pain to have to constantly clear the output to ensure I'm seeing the latest errors as well as checking to see I'm not half way scrolled up the output window (subsequently missing the latest errors).

This issue proposes the addition of a new button in the appearing toolbar on the left:
![Y6Ada5T](https://github.com/user-attachments/assets/cf42375b-3d8d-4371-888b-50fc5a332ca8)

The icon could be a broom / brush or a bin etc.

There could be a keybind for this!

When toggled, it'll  **clear the Studio output _whenever any story you're viewing is updated_** using the `ClearOutput` method of the `LogService`. Otherwise, when not active the output's contents will be retained.

**Comment by PepeElToro41** [comment]
I mean, it could be useful sometimes, but Im not sure if adding a button for it is really worth it.

For context, new version is getting a new toolbar with quite more buttons, and it's already getting a little messy. Adding this button would make it worse

 
![image](https://github.com/user-attachments/assets/0ec51a77-6aa1-4730-9402-4c917d1f7bf7)

**Comment by PepeElToro41** [comment]
New version is getting a dropdown, so I can propose moving it there instead.

also, how would this be handled when you have multiple stories?

![image](https://github.com/user-attachments/assets/13c08de2-5680-425f-aa1f-f3be9e166ffb)

**Comment by Nidoxs** [comment]
> New version is getting a dropdown, so I can suggest moving it there instead.
> 
> also, how would this be handled when you have multiple stories?. Maybe this function can be disabled when you have multiple stories mounted, or just let it clear it anyway
> 
> ![image](https://private-user-images.githubusercontent.com/101070050/369237956-13c08de2-5680-425f-aa1f-f3be9e166ffb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MzQ4NDUsIm5iZiI6MTcyNjgzNDU0NSwicGF0aCI6Ii8xMDEwNzAwNTAvMzY5MjM3OTU2LTEzYzA4ZGUyLTU2ODAtNDI1Zi1hYTFmLWYzYmU5ZTE2NmZmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxMjE1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MDY1MjA3OTBmZTNkZWQyMzllMjNlZGQwYTYxMDUzZTA2MzU5ZDg0NDg5MDAzNzk4NWJhMDlmOGVmNDIxOTBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nolu_L_Myal7cbxjFsmnpeE2mCOTTVp0j_gqfkAtQ90)

This is awesome! Yeah I agree that the toolbar there is getting filled, so this dropdown would be great to house more specific things that don't necessarily need to go in the toolbar.

When it comes to the behaviour when using multi-mount, I think it should only clear the output when the story you've got **selected** currently changes. It could also clear the output when **any** of the currently visible stories is changed, but it could be confusing if you forget you've got that enabled.

Perhaps there could be two settings, one to enable the behaviour and another to specify what happens in multi-mount mode.

**Comment by PepeElToro41** [comment]
Added the option in the dropdown https://github.com/PepeElToro41/ui-labs/commit/a009a4b090129fcb10309261c14cf8660592cdda
