### ISSUE TITLE
Summary text should have `TextWrapped` enabled

### ISSUE THREAD

**Issue by Nidoxs** [PepeElToro41/ui-labs#47]
The summary text for a story is really useful but it seems the text does not wrap if it's longer than the width of the window, this issue proposes to set the `TextWrapped` default to `true`

![ZuU5WbY](https://github.com/user-attachments/assets/92f9b02d-8c87-4e7f-8217-ee4d08976af3)

**Comment by PepeElToro41** [comment]
Oh, never noticed that, thanks for pointing out!
