### ISSUE TITLE
Make `Summary` and `Controls` tab text bold

### ISSUE THREAD

**Issue by Nidoxs** [PepeElToro41/ui-labs#48]
**Before:**
![n8yncNN](https://github.com/user-attachments/assets/ce0e1520-e9f0-43dc-8396-1e0f6f0299d7)

**After:**
![heOz5Ow](https://github.com/user-attachments/assets/29d4d82e-25a0-47fa-88be-cf4535cc880f)

I feel this is a little easier on the eyes and stands out better. (Sorry for such a pedantic issue, thanks!)

**Comment by PepeElToro41** [comment]
yeah, I think it's a good idea I'll add it for the next update
