### ISSUE TITLE
Create a contribution guide in the documentation

### ISSUE THREAD

**Issue by Nidoxs** [PepeElToro41/ui-labs#49]
Such documentation would help those who want to contribute to UI Labs, by providing a clear and structured set of guidelines and general information about contributing to the plugin. This could probably just go into a `Contributing` page in the documentation.

**Comment by PepeElToro41** [comment]
You are right

**Comment by PepeElToro41** [comment]
Guide created [Here](https://github.com/PepeElToro41/ui-labs/blob/main/CONTRIBUTING.md)
