### ISSUE TITLE
Option to persist "View In Viewport" selection

### ISSUE THREAD

**Issue by Nidoxs** [PepeElToro41/ui-labs#52]
When I use the studio viewport to render stories with Hoarcekat, any other stories I want to view next will **continue to render** in the viewport (as the option persists between stories). It seems UI Labs resets that state when a new story is selected, causing the next story to hop back to the plugin widget view.

I appreciate some may prefer the next story to return to the plugin widget, so perhaps this is another entry for your new dropdown menu / settings which users can choose between.😄

**Comment by PepeElToro41** [comment]
yes, this is changed in the new version, when you mount a new story it will remember the last `ViewOnViewport` state.

Probably an extra option wouldnt hurt
