### ISSUE TITLE
Some settings should save using `Plugin:SetSetting()`

### ISSUE THREAD

**Issue by Nidoxs** [PepeElToro41/ui-labs#55]
It'd be neat for certain options to persist across sessions when opening ui-labs. One setting that comes to mind immediately for me is the floating toolbar on the left. 

Most of the time I'll just anchor it, but I have to do this every time I open the widget. This change would ensure that some of the React components (or perhaps more appropriately, the contexts) attempt to restore settings using `Plugin:GetSetting()`.

While this is trivial, it further improves UX.

**Comment by PepeElToro41** [comment]
yep, should be merged, I also added more things to save [here](https://github.com/PepeElToro41/ui-labs/commit/7849de3d0429120d93ae4e83e19b34a622e33011#diff-039239a2c3bc05d5f0d9ac2fe527f6c08dfd7fa0b26fad3e2d562359b6ad8f5e)
